name: Checks for lint errors
on:
  push:
    branches:
      - master
jobs:
    changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all}}
      jsandjsx: ${{ steps.changes.outputs.jsandjsx }}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
          echo "::set-output name=jsandjsx::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep -E \"(.js$|.jsx$)\")" | xargs)"
  build:
    runs-on: ubuntu-latest
    # require the first job to have ran
    needs: changedfiles
    # only run there are changed files
    if: ${{needs.changedfiles.outputs.ts}}
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: echo changed files
        run: echo ${{needs.changedfiles.outputs.jsandjsx}}
      - name: List all modified files
        run: |
          for file in "${{ needs.changedfiles.outputs.jsandjsx }}"; do
            echo "$file was modified"
            yarn run eslint $file  --ext .js,.jsx
          done
